/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type TermsPage = {
  _id: string;
  _type: "termsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroTitle?: string;
  heroText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  heroImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  textBlock?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type PrivacyPage = {
  _id: string;
  _type: "privacyPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroTitle?: string;
  heroText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  heroImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  textBlock?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type Occasion = {
  _id: string;
  _type: "occasion";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  hasCateringLink?: boolean;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroTitle: string;
  heroText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  heroImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  textBlock?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type RoomNavigation = {
  _id: string;
  _type: "roomNavigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  roomNavItems?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "room";
  }>;
};

export type FrontPage = {
  _id: string;
  _type: "frontPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  descriptionBlock?: {
    text: string;
  };
  mainFeaturedRoom: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "room";
  };
  featuredRooms?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "room";
  }>;
  otherRooms?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "room";
  }>;
};

export type Room = {
  _id: string;
  _type: "room";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  roomType: "Banquet Hall" | "Meeting Room";
  roomThemeColor: "orange" | "green";
  area: number;
  capacity: number;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  prices: Array<{
    priceTitle: string;
    timeFrame: "hourly" | "halfday" | "fullday";
    price: number;
    _type: "price";
    _key: string;
  }>;
  priceDescription?: string;
  roomCategories?: Array<string>;
  facilities?: Array<string>;
  extraImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  seatingPlans?: Array<string>;
  occasions?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "occasion";
  }>;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  metaDescription: string;
  url: string;
  logoImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  localBusinessImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  streetAddress: string;
  addressLocality: string;
  addressMapUrl: string;
  postCode: string;
  phoneNumber: string;
  openingHours: string;
  socials?: Array<string>;
  services?: {
    serviceName?: string;
    serviceDescription?: string;
    serviceCategories?: Array<string>;
  };
  memberDiscount?: {
    text: string;
    linkText: string;
    linkUrl: string;
  };
  aboutUs?: {
    heading: string;
    text: string;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
  contactInfo?: {
    heading: string;
    text: string;
  };
  bookingAssistance?: {
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    text: string;
    email: string;
    phoneNumber: string;
  };
  rentingInfo?: {
    heading: string;
    text: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | TermsPage
  | PrivacyPage
  | Occasion
  | AboutPage
  | RoomNavigation
  | FrontPage
  | Room
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../meeting-place-website/src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == 'siteSettings'][0]
export type SITE_SETTINGS_QUERYResult = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  metaDescription: string;
  url: string;
  logoImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  localBusinessImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  streetAddress: string;
  addressLocality: string;
  addressMapUrl: string;
  postCode: string;
  phoneNumber: string;
  openingHours: string;
  socials?: Array<string>;
  services?: {
    serviceName?: string;
    serviceDescription?: string;
    serviceCategories?: Array<string>;
  };
  memberDiscount?: {
    text: string;
    linkText: string;
    linkUrl: string;
  };
  aboutUs?: {
    heading: string;
    text: string;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
  contactInfo?: {
    heading: string;
    text: string;
  };
  bookingAssistance?: {
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    text: string;
    email: string;
    phoneNumber: string;
  };
  rentingInfo?: {
    heading: string;
    text: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  };
} | null;
// Variable: HOME_QUERY
// Query: *[_type == 'frontPage']    {       descriptionBlock,      featuredRooms[]-> {        name,         slug,         roomType,         area,         capacity,         prices,         mainImage {          alt,          asset->{            _id,            url,            metadata {              lqip            }          }        }      },      mainFeaturedRoom-> {        name,         slug,         roomType,         area,         capacity,         prices,         mainImage {          alt,          asset->{            _id,            url,            metadata {              lqip            }          }        }      },      otherRooms[]-> {        name,         slug,         roomType,         area,         capacity,         prices,         mainImage {          alt,          asset->{            _id,            url,            metadata {              lqip            }          }        },        roomThemeColor      }    }[0]
export type HOME_QUERYResult = {
  descriptionBlock: {
    text: string;
  } | null;
  featuredRooms: Array<{
    name: string;
    slug: Slug;
    roomType: "Banquet Hall" | "Meeting Room";
    area: number;
    capacity: number;
    prices: Array<{
      priceTitle: string;
      timeFrame: "fullday" | "halfday" | "hourly";
      price: number;
      _type: "price";
      _key: string;
    }>;
    mainImage: {
      alt: string | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
        } | null;
      } | null;
    };
  }> | null;
  mainFeaturedRoom: {
    name: string;
    slug: Slug;
    roomType: "Banquet Hall" | "Meeting Room";
    area: number;
    capacity: number;
    prices: Array<{
      priceTitle: string;
      timeFrame: "fullday" | "halfday" | "hourly";
      price: number;
      _type: "price";
      _key: string;
    }>;
    mainImage: {
      alt: string | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
        } | null;
      } | null;
    };
  };
  otherRooms: Array<{
    name: string;
    slug: Slug;
    roomType: "Banquet Hall" | "Meeting Room";
    area: number;
    capacity: number;
    prices: Array<{
      priceTitle: string;
      timeFrame: "fullday" | "halfday" | "hourly";
      price: number;
      _type: "price";
      _key: string;
    }>;
    mainImage: {
      alt: string | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
        } | null;
      } | null;
    };
    roomThemeColor: "green" | "orange";
  }> | null;
} | null;
// Variable: ROOM_QUERY
// Query: {  "currentRoom": *[    _type == "room"    && defined(slug.current)    && slug.current == $slug  ]{    name,     slug,     roomType,     area,     capacity,     prices,     mainImage {          alt,          asset->{            _id,            url,            metadata {              lqip            }          }        },     description,     roomCategories,     roomThemeColor,     facilities,     gallery[]{      alt,      asset->{        _id,        url,        metadata {          dimensions {            width,            height          },          lqip        }      }    },      extraImage {          alt,          asset->{            _id,            url,            metadata {              lqip            }          }        },     seatingPlans,     occasions[]->{name, description, hasCateringLink},     priceDescription  }[0],  "roomNavigation": *[    _type == "roomNavigation"  ][0]{    roomNavItems[]-> {      name,       slug,       roomType,       area,       capacity,       prices,       mainImage {          alt,          asset->{            _id,            url,            metadata {              lqip            }          }        }    }  },}
export type ROOM_QUERYResult = {
  currentRoom: {
    name: string;
    slug: Slug;
    roomType: "Banquet Hall" | "Meeting Room";
    area: number;
    capacity: number;
    prices: Array<{
      priceTitle: string;
      timeFrame: "fullday" | "halfday" | "hourly";
      price: number;
      _type: "price";
      _key: string;
    }>;
    mainImage: {
      alt: string | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
        } | null;
      } | null;
    };
    description: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    roomCategories: Array<string> | null;
    roomThemeColor: "green" | "orange";
    facilities: Array<string> | null;
    gallery: Array<{
      alt: string | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
          lqip: string | null;
        } | null;
      } | null;
    }> | null;
    extraImage: {
      alt: string | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
        } | null;
      } | null;
    } | null;
    seatingPlans: Array<string> | null;
    occasions: Array<{
      name: string | null;
      description: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      hasCateringLink: boolean | null;
    }> | null;
    priceDescription: string | null;
  } | null;
  roomNavigation: {
    roomNavItems: Array<{
      name: string;
      slug: Slug;
      roomType: "Banquet Hall" | "Meeting Room";
      area: number;
      capacity: number;
      prices: Array<{
        priceTitle: string;
        timeFrame: "fullday" | "halfday" | "hourly";
        price: number;
        _type: "price";
        _key: string;
      }>;
      mainImage: {
        alt: string | null;
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
          } | null;
        } | null;
      };
    }> | null;
  } | null;
};
// Variable: ROOM_SLUG_QUERY
// Query: *[_type == 'room' && defined(slug.current)]{slug}
export type ROOM_SLUG_QUERYResult = Array<{
  slug: Slug;
}>;
// Variable: ROOM_METADATA_QUERY
// Query: *[_type == "room" && slug.current == $slug][0]{ name, slug, description, mainImage }
export type ROOM_METADATA_QUERYResult = {
  name: string;
  slug: Slug;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
} | null;
// Variable: ABOUT_QUERY
// Query: *[_type == 'aboutPage']{heroTitle, heroText, heroImage, textBlock, images}[0]
export type ABOUT_QUERYResult = {
  heroTitle: string;
  heroText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  heroImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  textBlock: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  images: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
} | null;
// Variable: PRIVACY_QUERY
// Query: *[_type == 'privacyPage']{heroTitle, heroText, heroImage, textBlock, images}[0]
export type PRIVACY_QUERYResult = {
  heroTitle: string | null;
  heroText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  heroImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  textBlock: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  images: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
} | null;
// Variable: TERMS_QUERY
// Query: *[_type == 'termsPage']{heroTitle, heroText, heroImage, textBlock, images}[0]
export type TERMS_QUERYResult = {
  heroTitle: string | null;
  heroText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  heroImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  textBlock: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  images: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
} | null;
// Variable: NAVIGATION_QUERY
// Query: *[_type == 'roomNavigation'][0]{roomNavItems[]-> {      name, slug, roomType, area, capacity, prices, mainImage {          alt,          asset->{            _id,            url,            metadata {              lqip            }          }        }    }}
export type NAVIGATION_QUERYResult = {
  roomNavItems: Array<{
    name: string;
    slug: Slug;
    roomType: "Banquet Hall" | "Meeting Room";
    area: number;
    capacity: number;
    prices: Array<{
      priceTitle: string;
      timeFrame: "fullday" | "halfday" | "hourly";
      price: number;
      _type: "price";
      _key: string;
    }>;
    mainImage: {
      alt: string | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
        } | null;
      } | null;
    };
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n*[_type == 'siteSettings'][0]\n  ": SITE_SETTINGS_QUERYResult;
    "\n  *[_type == 'frontPage']\n    { \n      descriptionBlock,\n      featuredRooms[]-> {\n        name, \n        slug, \n        roomType, \n        area, \n        capacity, \n        prices, \n        mainImage {\n          alt,\n          asset->{\n            _id,\n            url,\n            metadata {\n              lqip\n            }\n          }\n        }\n      },\n      mainFeaturedRoom-> {\n        name, \n        slug, \n        roomType, \n        area, \n        capacity, \n        prices, \n        mainImage {\n          alt,\n          asset->{\n            _id,\n            url,\n            metadata {\n              lqip\n            }\n          }\n        }\n      },\n      otherRooms[]-> {\n        name, \n        slug, \n        roomType, \n        area, \n        capacity, \n        prices, \n        mainImage {\n          alt,\n          asset->{\n            _id,\n            url,\n            metadata {\n              lqip\n            }\n          }\n        },\n        roomThemeColor\n      }\n    }[0]\n": HOME_QUERYResult;
    '{\n  "currentRoom": *[\n    _type == "room"\n    && defined(slug.current)\n    && slug.current == $slug\n  ]{\n    name, \n    slug, \n    roomType, \n    area, \n    capacity, \n    prices, \n    mainImage {\n          alt,\n          asset->{\n            _id,\n            url,\n            metadata {\n              lqip\n            }\n          }\n        }, \n    description, \n    roomCategories, \n    roomThemeColor, \n    facilities, \n    gallery[]{\n      alt,\n      asset->{\n        _id,\n        url,\n        metadata {\n          dimensions {\n            width,\n            height\n          },\n          lqip\n        }\n      }\n    },  \n    extraImage {\n          alt,\n          asset->{\n            _id,\n            url,\n            metadata {\n              lqip\n            }\n          }\n        }, \n    seatingPlans, \n    occasions[]->{name, description, hasCateringLink}, \n    priceDescription\n  }[0],\n  "roomNavigation": *[\n    _type == "roomNavigation"\n  ][0]{\n    roomNavItems[]-> {\n      name, \n      slug, \n      roomType, \n      area, \n      capacity, \n      prices, \n      mainImage {\n          alt,\n          asset->{\n            _id,\n            url,\n            metadata {\n              lqip\n            }\n          }\n        }\n    }\n  },\n}': ROOM_QUERYResult;
    "\n  *[_type == 'room' && defined(slug.current)]{slug}\n": ROOM_SLUG_QUERYResult;
    '*[_type == "room" && slug.current == $slug][0]{ name, slug, description, mainImage }': ROOM_METADATA_QUERYResult;
    "\n  *[_type == 'aboutPage']{heroTitle, heroText, heroImage, textBlock, images}[0]\n": ABOUT_QUERYResult;
    "\n  *[_type == 'privacyPage']{heroTitle, heroText, heroImage, textBlock, images}[0]\n": PRIVACY_QUERYResult;
    "\n  *[_type == 'termsPage']{heroTitle, heroText, heroImage, textBlock, images}[0]\n": TERMS_QUERYResult;
    "\n*[_type == 'roomNavigation'][0]{roomNavItems[]-> {\n      name, slug, roomType, area, capacity, prices, mainImage {\n          alt,\n          asset->{\n            _id,\n            url,\n            metadata {\n              lqip\n            }\n          }\n        }\n    }}\n": NAVIGATION_QUERYResult;
  }
}
