import { cn } from "@/lib/utils";

export default function SvgHestesko({
  className,
  ...props
}: React.ComponentProps<"svg">) {
  return (
    <svg
      className={cn("h-[17.8125rem] w-[32.125rem]", className)}
      viewBox="0 0 514 285"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect
        x="104"
        y="218"
        width="14"
        height="16"
        rx="1"
        transform="rotate(90 104 218)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="90"
        y="218"
        width="14"
        height="2"
        rx="1"
        transform="rotate(90 90 218)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="104"
        y="191"
        width="14"
        height="16"
        rx="1"
        transform="rotate(90 104 191)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="90"
        y="191"
        width="14"
        height="2"
        rx="1"
        transform="rotate(90 90 191)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="104"
        y="164"
        width="14"
        height="16"
        rx="1"
        transform="rotate(90 104 164)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="90"
        y="164"
        width="14"
        height="2"
        rx="1"
        transform="rotate(90 90 164)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="104"
        y="137"
        width="14"
        height="16"
        rx="1"
        transform="rotate(90 104 137)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="90"
        y="137"
        width="14"
        height="2"
        rx="1"
        transform="rotate(90 90 137)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="104"
        y="110"
        width="14"
        height="16"
        rx="1"
        transform="rotate(90 104 110)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="90"
        y="110"
        width="14"
        height="2"
        rx="1"
        transform="rotate(90 90 110)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="104"
        y="83"
        width="14"
        height="16"
        rx="1"
        transform="rotate(90 104 83)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="90"
        y="83"
        width="14"
        height="2"
        rx="1"
        transform="rotate(90 90 83)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="104"
        y="56"
        width="14"
        height="16"
        rx="1"
        transform="rotate(90 104 56)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="90"
        y="56"
        width="14"
        height="2"
        rx="1"
        transform="rotate(90 90 56)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="130"
        y="50"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 130 50)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="130"
        y="36"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 130 36)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="157"
        y="50"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 157 50)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="157"
        y="36"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 157 36)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="184"
        y="50"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 184 50)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="184"
        y="36"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 184 36)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="211"
        y="50"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 211 50)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="211"
        y="36"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 211 36)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="238"
        y="50"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 238 50)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="238"
        y="36"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 238 36)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="265"
        y="50"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 265 50)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="265"
        y="36"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 265 36)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="292"
        y="50"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 292 50)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="292"
        y="36"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 292 36)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="319"
        y="50"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 319 50)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="319"
        y="36"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 319 36)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="346"
        y="50"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 346 50)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="346"
        y="36"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 346 36)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="373"
        y="50"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 373 50)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="373"
        y="36"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 373 36)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="400"
        y="50"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 400 50)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="400"
        y="36"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 400 36)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="156"
        y="48"
        width="255"
        height="53"
        fill="#FFFBF6"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="386"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="386"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="359"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="359"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="332"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="332"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="305"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="305"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="278"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="278"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="251"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="251"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="224"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="224"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="197"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="197"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="170"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="170"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="143"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="143"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="116"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="116"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="156"
        y="187"
        width="255"
        height="53"
        fill="#FFFBF6"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="156"
        y="48"
        width="192"
        height="53"
        transform="rotate(90 156 48)"
        fill="#FFFBF6"
        stroke="currentColor"
        strokeWidth="2"
      />
    </svg>
  );
}
