import { cn } from "@/lib/utils";

export default function SvgKlasserom({
  className,
  ...props
}: React.ComponentProps<"svg">) {
  return (
    <svg
      className={cn("h-[17.8125rem] w-[32.125rem]", className)}
      viewBox="0 0 514 285"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect
        x="386"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="386"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="359"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="359"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="348"
        y="207"
        width="63"
        height="33"
        fill="#FFFBF6"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="386"
        y="157"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="386"
        y="171"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="359"
        y="157"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="359"
        y="171"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="348"
        y="126"
        width="63"
        height="33"
        fill="#FFFBF6"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="386"
        y="76"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="386"
        y="90"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="359"
        y="76"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="359"
        y="90"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="348"
        y="45"
        width="63"
        height="33"
        fill="#FFFBF6"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="305"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="305"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="278"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="278"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="267"
        y="207"
        width="63"
        height="33"
        fill="#FFFBF6"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="305"
        y="157"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="305"
        y="171"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="278"
        y="157"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="278"
        y="171"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="267"
        y="126"
        width="63"
        height="33"
        fill="#FFFBF6"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="305"
        y="76"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="305"
        y="90"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="278"
        y="76"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="278"
        y="90"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="267"
        y="45"
        width="63"
        height="33"
        fill="#FFFBF6"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="224"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="224"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="197"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="197"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="186"
        y="207"
        width="63"
        height="33"
        fill="#FFFBF6"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="224"
        y="157"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="224"
        y="171"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="197"
        y="157"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="197"
        y="171"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="186"
        y="126"
        width="63"
        height="33"
        fill="#FFFBF6"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="224"
        y="76"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="224"
        y="90"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="197"
        y="76"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="197"
        y="90"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="186"
        y="45"
        width="63"
        height="33"
        fill="#FFFBF6"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="143"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="143"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="116"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="116"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="105"
        y="207"
        width="63"
        height="33"
        fill="#FFFBF6"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="143"
        y="157"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="143"
        y="171"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="116"
        y="157"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="116"
        y="171"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="105"
        y="126"
        width="63"
        height="33"
        fill="#FFFBF6"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="143"
        y="76"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="143"
        y="90"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="116"
        y="76"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="116"
        y="90"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="105"
        y="45"
        width="63"
        height="33"
        fill="#FFFBF6"
        stroke="currentColor"
        strokeWidth="2"
      />
    </svg>
  );
}
