import { cn } from "@/lib/utils";

export default function SvgKino({
  className,
  ...props
}: React.ComponentProps<"svg">) {
  return (
    <svg
      className={cn("h-[17.8125rem] w-[32rem]", className)}
      viewBox="0 0 512 285"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 404 45)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 404 59)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 416 74)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 416 88)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 421 107)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 421 121)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 421 140)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 421 154)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 442 135)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 442 149)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 442 102)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 442 116)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 421 173)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 421 187)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 421 206)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 421 220)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 442 168)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 442 182)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 463 160)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 463 174)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 442 201)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 442 215)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 463 193)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 463 207)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 385 51)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 385 65)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 397 80)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 397 94)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 401 113)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 401 127)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 401 146)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 401 160)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 401 179)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 401 193)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 401 212)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 401 226)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 366 57)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 366 71)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 378 86)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 378 100)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 382 119)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 382 133)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 382 152)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 382 166)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 382 185)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 382 199)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 382 218)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 382 232)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 347 63)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 347 77)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 359 92)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 359 106)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 363 125)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 363 139)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 363 158)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 363 172)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 363 191)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 363 205)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 363 224)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 363 238)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 308 75)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 308 89)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 320 104)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 320 118)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 324 137)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 324 151)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 324 170)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 324 184)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 324 203)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 324 217)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 324 236)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 324 250)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 328 69)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 328 83)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 340 98)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 340 112)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 344 131)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 344 145)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 344 164)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 344 178)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 344 197)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 344 211)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 344 230)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 344 244)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 301 110)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 301 124)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 302 143)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 302 157)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 303 176)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 303 190)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 303 209)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 303 223)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="16"
        rx="1"
        transform="matrix(-1 0 0 1 303 242)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="-1"
        y="1"
        width="14"
        height="2"
        rx="1"
        transform="matrix(-1 0 0 1 303 256)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="107"
        y="46"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="107"
        y="60"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="95"
        y="75"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="95"
        y="89"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="90"
        y="108"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="90"
        y="122"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="90"
        y="141"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="90"
        y="155"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="69"
        y="136"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="69"
        y="150"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="69"
        y="103"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="69"
        y="117"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="90"
        y="174"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="90"
        y="188"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="90"
        y="207"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="90"
        y="221"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="69"
        y="169"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="69"
        y="183"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="48"
        y="161"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="48"
        y="175"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="69"
        y="202"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="69"
        y="216"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="48"
        y="194"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="48"
        y="208"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="126"
        y="52"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="126"
        y="66"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="114"
        y="81"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="114"
        y="95"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="110"
        y="114"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="110"
        y="128"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="110"
        y="147"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="110"
        y="161"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="110"
        y="180"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="110"
        y="194"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="110"
        y="213"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="110"
        y="227"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="145"
        y="58"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="145"
        y="72"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="133"
        y="87"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="133"
        y="101"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="129"
        y="120"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="129"
        y="134"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="129"
        y="153"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="129"
        y="167"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="129"
        y="186"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="129"
        y="200"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="129"
        y="219"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="129"
        y="233"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="164"
        y="64"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="164"
        y="78"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="152"
        y="93"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="152"
        y="107"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="148"
        y="126"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="148"
        y="140"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="148"
        y="159"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="148"
        y="173"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="148"
        y="192"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="148"
        y="206"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="148"
        y="225"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="148"
        y="239"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="203"
        y="76"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="203"
        y="90"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="191"
        y="105"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="191"
        y="119"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="187"
        y="138"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="187"
        y="152"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="187"
        y="171"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="187"
        y="185"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="187"
        y="204"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="187"
        y="218"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="187"
        y="237"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="187"
        y="251"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="183"
        y="70"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="183"
        y="84"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="171"
        y="99"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="171"
        y="113"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="167"
        y="132"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="167"
        y="146"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="167"
        y="165"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="167"
        y="179"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="167"
        y="198"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="167"
        y="212"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="167"
        y="231"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="167"
        y="245"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="210"
        y="111"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="210"
        y="125"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="209"
        y="144"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="209"
        y="158"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="208"
        y="177"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="208"
        y="191"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="208"
        y="210"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="208"
        y="224"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="208"
        y="243"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="208"
        y="257"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
    </svg>
  );
}
