import { cn } from "@/lib/utils";

export default function SvgLangbord({
  className,
  ...props
}: React.ComponentProps<"svg">) {
  return (
    <svg
      className={cn("h-[17.8125rem] w-[32.125rem]", className)}
      viewBox="0 0 514 285"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect
        x="130"
        y="50"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 130 50)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="130"
        y="36"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 130 36)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="386"
        y="99"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="386"
        y="113"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="157"
        y="50"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 157 50)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="157"
        y="36"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 157 36)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="359"
        y="99"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="359"
        y="113"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="184"
        y="50"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 184 50)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="184"
        y="36"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 184 36)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="332"
        y="99"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="332"
        y="113"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="211"
        y="50"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 211 50)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="211"
        y="36"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 211 36)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="305"
        y="99"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="305"
        y="113"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="238"
        y="50"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 238 50)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="238"
        y="36"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 238 36)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="278"
        y="99"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="278"
        y="113"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="265"
        y="50"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 265 50)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="265"
        y="36"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 265 36)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="251"
        y="99"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="251"
        y="113"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="292"
        y="50"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 292 50)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="292"
        y="36"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 292 36)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="224"
        y="99"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="224"
        y="113"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="319"
        y="50"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 319 50)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="319"
        y="36"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 319 36)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="197"
        y="99"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="197"
        y="113"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="346"
        y="50"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 346 50)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="346"
        y="36"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 346 36)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="170"
        y="99"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="170"
        y="113"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="373"
        y="50"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 373 50)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="373"
        y="36"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 373 36)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="143"
        y="99"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="143"
        y="113"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="400"
        y="50"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 400 50)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="400"
        y="36"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 400 36)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="116"
        y="99"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="116"
        y="113"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="103"
        y="48"
        width="308"
        height="53"
        fill="#FFFBF6"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="130"
        y="189"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 130 189)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="130"
        y="175"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 130 175)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="386"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="386"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="157"
        y="189"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 157 189)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="157"
        y="175"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 157 175)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="359"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="359"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="184"
        y="189"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 184 189)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="184"
        y="175"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 184 175)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="332"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="332"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="211"
        y="189"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 211 189)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="211"
        y="175"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 211 175)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="305"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="305"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="238"
        y="189"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 238 189)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="238"
        y="175"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 238 175)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="278"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="278"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="265"
        y="189"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 265 189)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="265"
        y="175"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 265 175)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="251"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="251"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="292"
        y="189"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 292 189)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="292"
        y="175"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 292 175)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="224"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="224"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="319"
        y="189"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 319 189)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="319"
        y="175"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 319 175)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="197"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="197"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="346"
        y="189"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 346 189)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="346"
        y="175"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 346 175)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="170"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="170"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="373"
        y="189"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 373 189)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="373"
        y="175"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 373 175)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="143"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="143"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="400"
        y="189"
        width="14"
        height="16"
        rx="1"
        transform="rotate(-180 400 189)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="400"
        y="175"
        width="14"
        height="2"
        rx="1"
        transform="rotate(-180 400 175)"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="116"
        y="238"
        width="14"
        height="16"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="116"
        y="252"
        width="14"
        height="2"
        rx="1"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="103"
        y="187"
        width="308"
        height="53"
        fill="#FFFBF6"
        stroke="currentColor"
        strokeWidth="2"
      />
    </svg>
  );
}
